export const CREATE_CHANNEL_FAILED = 'CREATE_CHANNEL_FAILED'
export const CREATE_CHANNEL_REQUEST = 'CREATE_CHANNEL_REQUEST'
export const CREATE_CHANNEL_RESET = 'CREATE_CHANNEL_RESET'
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS'

export const CURRENT_CHANNEL_RESET = 'CURRENT_CHANNEL_RESET'
export const CURRENT_CHANNEL_SET = 'CURRENT_CHANNEL_SET'

export const HANDLE_CHANNEL = 'HANDLE_CHANNEL'

export const PUSH_CHANNEL_TO_CHANNELS = 'PUSH_CHANNEL_TO_CHANNELS'

export const SAVE_USER_TO_DB_FAILED = 'SAVE_USER_TO_DB_FAILED'
export const SAVE_USER_TO_DB_REQUEST = 'SAVE_USER_TO_DB_REQUEST'
export const SAVE_USER_TO_DB_SUCCESS = 'SAVE_USER_TO_DB_SUCCESS'

export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const USER_LOGOUT = 'USER_LOGOUT'
