export const SAVE_USER_TO_DB_FAILED = 'SAVE_USER_TO_DB_FAILED'
export const SAVE_USER_TO_DB_REQUEST = 'SAVE_USER_TO_DB_REQUEST'
export const SAVE_USER_TO_DB_SUCCESS = 'SAVE_USER_TO_DB_SUCCESS'

export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const USER_LOGOUT = 'USER_LOGOUT'
